global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'crypto-platform-monitor'

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
